### PR TITLE
Added shrink flashlight area when sliders are holded, similar to osu!std fl.

### PR DESCRIPTION
**Pull request by el-dasher**

### CODE REVIEW

**Comment by el-dasher** [comment]
Just to add here, still not done, i will try to make some things better.

**Comment by el-dasher** [comment]
It's done, it isn't nothing too complex anyways.

**Comment by EdrowsLuo** [comment]
It seems like a rough approch of flash light of osu!std.
If you want to want fl works in the same way osu!std does, maybe you should refer to the code of osu!lazer, but not simply guess some values.

**Comment by None1637** [comment]
I check the FL mod's code in osu!lazer(https://github.com/ppy/osu).

> // If a slider is in a tracking state, a further dim should be applied to the (remaining) visible portion of the playfield over a brief duration.

There is no change in the size of the visible area.

**Comment by el-dasher** [comment]
Oh, I will try to figure out a way to do with a dim version later then. Thanks.

**Comment by el-dasher** [comment]
Eh, i can't really do it, i think i will put tlearn java in my goals, i rlly want to contribute soething for this game...

**Pull request closed without merging**
