### PR TITLE
Fix grammar mistakes + make the readme more readable as a whole

### PR DESCRIPTION
**Pull request by rosenishere**

### CODE REVIEW

**Comment by rosenishere** [comment]
😡

**Comment by rosenishere** [comment]
nobody will beat me in size/s contributions
**I am the grammar man**

**Comment by Acivev** [comment]
> nobody will beat me in size/s contributions
> **I am the grammar man**
Sounds nice 👍

**Comment by rosenishere** [comment]
also, the "it was a game hatched" sounds a bit out of place, maybe something easier to understand?

**Comment by Acivev** [comment]
Its up to you, you can be creative ^^

**Comment by rosenishere** [comment]
### e
I'm dumb

**Comment by Beyley** [comment]
> also, the "it was a game hatched" sounds a bit out of place, maybe something easier to understand?

i actually dont see the issue with "it was a game hatched ..." it makes a lot of sense to me, and i see people use that phrase a lot  for games that are made by a community

**Comment by rosenishere** [comment]
aight beyley it is going to be like that

**Pull request merged**
