### PR TITLE
Upgrade engine to OpenGL ES 2.0

### LINKED ISSUE #330: Slider gradient integration.
I working on slider gradient visual for osu!droid and came up but a couple of issues due to the old Engine:

- In ES1 there's no near existence of shaders programs which are the base of the gradient effect, to approach the effect in modern versions a fragment shader for color interpolated by position is needed.

- Following the point above ES1 requires both vertex and color buffers by separate which means more memory usage under the hood for just a single slider.

There's 2 solutions I found for these:

- Use textures and texture coordinates which can lead in another issues, for example transparency effects must be applied through a layer due that we're working with a texture and not an absolute color unless we generate the texture dynamically at certain time (of course punishes performance). 

- Update to ES2 and use color per vertex solution. For this we can update AndEngine to "GLES2" branch, both versions are similar despite some minor changes that would require certain effort.

I've the algorithm to convert the slider path into vertices for both versions:

In ES1 it uses a separated color buffer but as expected it doesn't work properly, the only way to do gradient on ES1 is by using a texture and a texture coordinates buffer.

In ES2 it uses a single buffer for both vertices and the color as well a fragment shader to do the trick which comes natively with AndEngine in this case. (This has been tested)

I hear suggestions.

### PR DESCRIPTION
**Pull request by Reco1I**
In this PR I replacing the old AndEngine module which was based on OpenGL ES 1.0 branch to the OpenGL ES 2.0 implementation of the same engine.
There's some modifications that were re-applied to the engine as well recovery of removed features.

Benefits of the upgrade:

* Shader-based effects, closes #330 
* Sligth improvement of performance in some modern devices. OpenGL ES 2.0 has an improved graphics pipeline and a better memory management when it comes to buffering.
* Modern and chances to upgrade to OpenGL ES 3.0 in the future (I don't think it would be necessary).

The PR is currently on WIP, I'm working on port things to it. Consider this as a second attempt as the original upgrade was intended and tested with the old rimu! code base which had positive results.

Some notes about modifications made in the module besides the upgrade:

* All changes to the touch input handler made in #303 PR were re-applied.

**UPDATED 21/3**
Things pending to be fixed in order to set this PR as ready:

* Sliders body quad overlapping wedges are visible in sliders with complex paths.
* Storyboard is partially broken.
* ~~Particles doesn't show with certain blending functions, this includes Kiai particles in `MainScene` and `CursorTrail` particles.~~
Fixed with [f8aeca5](https://github.com/osudroid/osu-droid/pull/331/commits/f8aeca5dd8b5a0d0ae0c6657884c1a53fc8d2094)
* ~~Some score text sprites have wrong sizes between textures~~
Fixed with [3ce12d7](https://github.com/osudroid/osu-droid/pull/331/commits/3ce12d78f328465acbf4125139f4c56f548f9f7c)
* ~~When focusing the game from being in background sliders and video stops working, this may be due to the custom shaders those elements use.~~
Fixed with [62e4f30](https://github.com/osudroid/osu-droid/pull/331/commits/62e4f3057e4d6eddd34abfe7621d1a4204498a4e)
* ~~Support blending in the new particles system.~~
Fixed with [1eb4d63](https://github.com/osudroid/osu-droid/pull/331/commits/1eb4d63a0df4302d6bfa33497e940e2444710a0d)
* ~~Slider body rendering is completly removed due to uncompatibility, we should consider introduce newer slider rendering.~~
Fixed starting from [cb177b8](https://github.com/osudroid/osu-droid/pull/331/commits/cb177b839bd985816f9c81d03ba3caabfed9aa16)
* ~~Sometimes (happens weirdly) the VBO for texts produces an IOOBE, this require further investigation because it can be an engine bug.~~
Fixed with [1918204](https://github.com/osudroid/osu-droid/pull/331/commits/191820482d87b8d44d7c4f6af50d408156547166)
* ~~Sometimes approach circles appears with full opacity by small time before the circle shows.~~
Fixed with [7effdd9](https://github.com/osudroid/osu-droid/pull/331/commits/7effdd93e3431be8fcd8f1c0a046368035d9ce3f) (needs further testing). 
* ~~Classic spinner doesn't clip the metre sprite properly.~~
Fixed with [28bf98e](https://github.com/osudroid/osu-droid/pull/331/commits/28bf98ec8b2ce9eee7b59a9063b599f31069b641)
* ~~Blinking loading icon at game start.~~
Fixed with [93dca14](https://github.com/osudroid/osu-droid/pull/331/commits/93dca1419abbe01bdf3844a91339cc295c853715)
* ~~Video is not working.~~
Fixed with [ee9a6a8](https://github.com/osudroid/osu-droid/pull/331/commits/ee9a6a86421b9061d4e81d27ecb68b223736a7af)

For reviewers: 

* Commit [2e10760](https://github.com/osudroid/osu-droid/pull/331/commits/2e107607b4253eb8eb2e1f42441fb0e4573b5615) corresponds to the module change and re-addition of some missing features from the old module. No relevant changes were made here and of course, the project is not compilable here.
* Commits [3e0f9e9](https://github.com/osudroid/osu-droid/pull/331/commits/3e0f9e9235600bbc6047a983c795b112276b5f67) to [f0ebbe5](https://github.com/osudroid/osu-droid/pull/331/commits/f0ebbe54ecfbe8578c25ea3e3a57b10dea17b42a) corresponds to some additional changes and recovery of missing features.
* Commit [eeb901f](https://github.com/osudroid/osu-droid/pull/331/commits/eeb901fe3fe399129fa3bf5775ced708e02ec9c5) and newer corresponds to actual game changes adopting the new engine module, most of them are just `import`s refactors. At this point the project is now compilable and *playable*.

### CODE REVIEW

**Comment by Acivev** [comment]
its still missing some files, like here [ utils/adt/io](https://github.com/nicolasgramlich/AndEngine/tree/GLES2/src/org/andengine/util/adt/io)

**Comment by Reco1I** [comment]
> its still missing some files, like here [ utils/adt/io](https://github.com/nicolasgramlich/AndEngine/tree/GLES2/src/org/andengine/util/adt/io)

Thanks to point that, I don't know why that is missing since I downloaded the repository from there.

**Comment by ammarasyad** [comment]
Well this is a surprise.

**Comment by Reco1I** [comment]
**UPDATED 18/2**

Sliders rendering has been successfully rewritten, yet there's some things to fix and optimization to apply over it.

**Comment by Reco1I** [comment]
Note: I removed hint system.

**Comment by Reco1I** [comment]
> since i researched, it's advisable to utilize the [AndEngineAnchorCenter](https://github.com/nicolasgramlich/AndEngine/tree/GLES2-AnchorCenter) instead of the Gles2 branch, as it represents the latest and greatest. May you can look if its right but my guess it is^^

Upgrade to `GLES2-AnchorCenter` branch requires a major effort because the entity origin (anchor) being the center isn't the only change there. For example it also changes the whole coordinate system origin from lower-bottom-left to upper-top-left, that is, we have to flip coordinates when placing object as well when calculating vertices for sliders.
And personally I don't think it is the "greatest" since it just only introduces an offset/origin system as difference from the previous. Both are using OpenGL ES 2.0.

**Comment by Reco1I** [comment]
More preview of the progress: 

https://github.com/osudroid/osu-droid/assets/103213881/8368e328-f189-4ae6-b76c-a077366dce9c

There's still things to fix yet.

**Comment by Reco1I** [comment]
List of pending fixes is updated.

**Comment by Reco1I** [comment]
Closing this for now, eventually I gonna PRd this again with a rebased version.

**Pull request closed without merging**
